version: '3.8'
services:
  db:
    image: mariadb:10.5
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD:
    volumes:
      - ./mariadb:/var/lib/mysql
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ROOT: /usr/src/rails_demosite
    image: rails_demosite
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/rails_demosite
    environment:
      RAILS_ENV: development
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD:
    depends_on:
      - db
    tty: true
    stdin_open: true
